# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "34788b49b8f9d819cfcb09da447b0d8586c63ad1acd469a1e446"    #这个可以复用 也可以自己生成
  limiter: false
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
search:
  formats:
    - html
    - json   ##开启json模式 方便被llm调用

engines:
# 启用默认禁用的国内引擎
  - name: baidu
    categories:
      - web
      - news
      - general
    engine: baidu
    shortcut: bd
    timeout: 9.0
    disabled: false


  - name: 360search
    categories:
      - web
      - news
      - general
    engine: 360search
    shortcut: 360so
    timeout: 9.0
    disabled: false



# 禁用默认启用的外国搜索引擎
  - name: archlinuxwiki
    engine: archlinux
    disabled: true
  - name: duckduckgo
    engine: duckduckgo
    distabled: true
  - name: github
    engine: github
    shortcut: gh
    disabled: true
  - name: wikipedia
    engine: wikipedia
    disabled: true
  - name: wikidata
    engine: wikidata
    disabled: true
  - name: google
    engine: google
    disabled: true
  - name: youtube
    engine: youtube_noapi
    disabled: true
  - name: duckduckgo
    engine: duckduckgo
    disabled: true
  - name: qwant
    engine: qwant
    disabled: true
  - name: brave
    engine: brave
    disabled: true
  - name: startpage
    engine: startpage
    disabled: true
  - name: currency
    engine: currency
    disabled: true